tap "caskroom/cask"
tap "homebrew/bundle"
tap "homebrew/completions"

# dropbox first to get syncing starting...
cask "dropbox"

# 1password and chrome to get them setup
cask "1password"
cask "google-chrome"

# dev tools
cask "iterm2"
cask "atom"
cask "virtualbox"
cask "vagrant"

brew "ack"
brew "bash"
brew "bash-completion"
brew "ffmpeg"
brew "findutils"
brew "flac"
brew "git"
brew "hub"
brew "lame"
brew "macvim", args: ['with-lua', 'with-custom-icons', 'with-override-system-vim']
brew "node"
brew "rbenv"
# http://blog.burntsushi.net/ripgrep/
# brew "https://raw.githubusercontent.com/BurntSushi/ripgrep/master/pkg/brew/ripgrep.rb"
brew "ruby-build"
brew "python"
brew "sqlite"
brew "tig"
brew "tree"
brew "wget"
brew "unrar"
brew "youtube-dl"

# the rest of the apps
cask "1password"
cask "audacity"
cask "caffeine"
cask "cloak"
cask "divvy"
cask "fantastical"
cask "flux"
cask "handbrake"
cask "java"
cask "kindlegen"
cask "minecraft"
cask "nvalt"
cask "graphiql"
cask "screenhero"
cask "sizeup"
cask "slack"
cask "steam"
cask "the-unarchiver"
cask "todoist"
cask "transmission"
cask "vlc"
cask "yubiswitch"
